# Generated by Django 4.2.4 on 2023-09-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuskbookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='service',
            new_name='schedule',
        ),
    ]
