# Generated by Django 4.2.4 on 2023-09-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuskbookings', '0002_rename_service_staff_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingschedule',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
