# Generated by Django 4.2.4 on 2023-09-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuskbookings", "0003_bookingschedule_accepted"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
